DRIVER_CLASS = org.postgresql.Driver

# Neon JDBC URL (clean version)
CONNECTION_STRING = jdbc:postgresql://ep-snowy-block-a1ku8qi3-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

# Credentials
USERNAME = neondb_owner
PASSWORD = npg_c1KHeSm7nAhT










#DRIVER_CLASS=org.postgresql.Driver
#CONNECTION_STRING=jdbc:postgresql://ep-snowy-block-a1ku8qi3-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
#USERNAME=neondb_owner
#PASSWORD=npg_c1KHeSm7nAhT

